2021-02-16 23:35:30,681 ERROR: Exception on /auth/reset_password_request [POST] [in F:\anaconda\envs\python38\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "F:\anaconda\envs\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\python work\microblogs\app\auth\routes.py", line 62, in reset_password_request
    send_password_reset_email(user)
  File "E:\python work\microblogs\app\auth\email.py", line 12, in send_password_reset_email
    send_email(_('[Microblog] Reset Your Password'),
  File "E:\python work\microblogs\app\email.py", line 20, in send_email
    ctx = app.app_context()
NameError: name 'app' is not defined
2021-02-16 23:36:24,271 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-16 23:36:30,186 ERROR: Exception on /auth/reset_password_request [POST] [in F:\anaconda\envs\python38\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "F:\anaconda\envs\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\python work\microblogs\app\auth\routes.py", line 62, in reset_password_request
    send_password_reset_email(user)
  File "E:\python work\microblogs\app\auth\email.py", line 12, in send_password_reset_email
    send_email(_('[Microblog] Reset Your Password'),
  File "E:\python work\microblogs\app\email.py", line 20, in send_email
    ctx = app.app_context()
NameError: name 'app' is not defined
2021-02-16 23:37:26,166 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-16 23:37:32,324 ERROR: Exception on /auth/reset_password_request [POST] [in F:\anaconda\envs\python38\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "F:\anaconda\envs\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\python work\microblogs\app\auth\routes.py", line 62, in reset_password_request
    send_password_reset_email(user)
  File "E:\python work\microblogs\app\auth\email.py", line 12, in send_password_reset_email
    send_email(_('[Microblog] Reset Your Password'),
  File "E:\python work\microblogs\app\email.py", line 20, in send_email
    ctx = app.app_context()
NameError: name 'app' is not defined
2021-02-16 23:38:15,174 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-16 23:39:36,065 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-16 23:43:41,104 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-16 23:46:53,784 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-16 23:49:45,052 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-16 23:50:34,781 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-16 23:54:37,241 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-16 23:55:59,099 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-16 23:56:31,754 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 00:00:00,835 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 00:04:33,584 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 00:08:18,425 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 00:09:05,656 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 00:14:25,169 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 00:18:53,377 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 00:22:31,056 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 00:25:15,010 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 00:26:43,064 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 00:28:16,560 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 00:30:45,693 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 00:32:54,834 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 00:37:09,984 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 00:39:38,951 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 00:44:52,997 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 00:50:54,175 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 00:51:27,822 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 08:54:19,109 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 09:00:10,755 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 09:02:51,017 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 09:03:00,756 ERROR: Exception on /auth/reset_password_request [POST] [in F:\anaconda\envs\python38\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "F:\anaconda\envs\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\anaconda\envs\python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\python work\microblogs\app\auth\routes.py", line 62, in reset_password_request
    send_password_reset_email(user)
  File "E:\python work\microblogs\app\auth\email.py", line 13, in send_password_reset_email
    sender=current_app.config['ADMINS'][0],
KeyError: 'ADMINS'
2021-02-17 09:05:34,446 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 09:13:04,648 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 09:17:19,446 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 09:19:25,220 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 09:21:41,251 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 09:46:04,155 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 09:48:42,190 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 09:50:00,882 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 09:57:48,027 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 09:58:23,322 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 09:59:10,247 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 10:02:51,269 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 10:03:24,078 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 10:04:56,165 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
2021-02-17 10:05:55,618 INFO: Microblog startup [in E:\python work\microblogs\app\__init__.py:62]
